### ISSUE TITLE
seq-monkey数据集下载不到，请问有人有网盘链接吗?

### ISSUE THREAD

**Issue by wqlxx** [jingyaogong/minimind#10]
seq-monkey数据集下载不到，请问有人有网盘链接吗?

**Comment by jingyaogong** [comment]
[Baidu网盘](https://pan.baidu.com/s/114F1k3eksiWCOQLvaT3RYQ?pwd=6666)

其实大概两小时前注意到了，出门问问官方网盘确实打不开了

然后上传到百度网盘花了两小时，31GB，文件有点大....

**Comment by wqlxx** [comment]
太感谢了
