### ISSUE TITLE
请问预训练需要完整跑完20个epoch吗

### ISSUE THREAD

**Issue by PshySimon** [jingyaogong/minimind#101]
训练完2个epoch发现复读机现象比较严重，不知道训练多少个epoch就可以用了==20个感觉也太久了，大佬能解答一下嘛

**Comment by ChinanBoys** [comment]
可以直接下载作者大大的权重文件的，我差不多训练了5个epoch吧，感觉没有复读机现象

**Comment by PshySimon** [comment]
> 可以直接下载作者大大的权重文件的，我差不多训练了5个epoch吧，感觉没有复读机现象

==我本身就是在复现预训练的效果，目前感觉0.02B的模型几个测试用例基本都有重复片段

**Comment by PshySimon** [comment]
我现在正在跑第五轮，eval的结果是这样的：
模型参数: 26.878464 百万 = 0.026878464 B (Billion)
问题： 椭圆和圆的区别
回答：是，不锈钢椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的，椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的。
椭圆的表面是黑色，而椭圆的表面是黑色的，而椭圆的表面是黑色的。椭圆的表面是黑色的，而椭圆的表面是黑色的。
椭圆的表面是黑色的，而椭圆的表面是黑色的。椭圆的表面是黑色的，而椭圆的表面是黑色的。椭圆的表面是黑色的，而椭圆的表面是黑色的，而椭圆的表面是黑色的。

5.698611497879028 s
问题： 中国关于马克思主义基本原理
回答：的论述，是对马克思主义基本原理的阐述，是对中国共产党的理论创新、实践创新、理论创新、制度创新、制度创新、实践创新等方面的论述。
马克思主义基本原理是中国共产党的理论创新、实践创新、实践创新、理论创新和制度创新的基本理论。中国共产党的理论创新、实践创新和理论创新是马克思主义基本原理的重要组成部分。
马克思主义基本原理是马克思主义基本原理的理论创新、实践创新、实践创新和理论创新，也是马克思主义基本原理的理论创新。

3.1235642433166504 s
问题： 人类大脑的主要功能是
回答：利用脑神经细胞的能量和能量。脑细胞的能量和能量都与大脑产生强烈的共振，大脑的发育是不可逆的。脑细胞的能量和能量和能量都与大脑的作用有关。大脑的发育与人类大脑的功能密切相关。大脑的发育与人类大脑有关。大脑在大脑发育的过程中起着重要作用。大脑的发育与人类大脑的发育和人类大脑的发育是不可逆的。大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育是不可逆的。大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育、人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育和人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑的发育、人类大脑的发育与人类大脑的发育与人类大脑的发育与人类大脑

11.26783013343811 s
问题： 万有引力是
回答：其中的一种，万有引力是其中的一种。

0.26586103439331055 s
问题： 世界上人口最多的国家是
回答：英格兰，英格兰人口最多的国家是阿根廷，英格兰人口最多的国家是英格兰。
英格兰是英格兰最大的国家，英格兰人口最多的国家是英格兰，英格兰人口最多的国家是英格兰，英格兰人口最多的国家是阿根廷，英格兰人口最多的国家是德国，英格兰人口最多的国家是德国，英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰，英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是德国人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最多的国家是英格兰人口最少的国家是英格兰人口最多的国家是英格兰人口最多的国家是英

11.164605379104614 s
问题： DNA的全称是
回答：DNA基因，由DNA基因、DNA基因、DNA基因、生物信息和环境基因、基因组的相互关系、基因检测方法、基因检测方法、基因检测方法以及基因检测方法等组成。
DNA基因的定义：DNA基因是人类的基因，由DNA基因、DNA基因组成。
DNA基因与DNA的关系：DNA基因是基因和DNA基因的相互关系、相互联系，相互关系、相互关系、共同作用。在临床中，DNA基因的表达、转化、分化、扩散是DNA基因的相互关系、相互关系、相互关系、相互关系、共同作用的关系。

3.2376859188079834 s
问题： 数学中π的值大约是
回答：0-10的。

0.12038397789001465 s
问题： 世界上最高的山峰是
回答：世界上最大的极山，也是世界上最高的山峰之一。

0.33959460258483887 s
问题： 太阳系中最大的行星是
回答：月球，月球的直径约为1.8公里，而月球的直径为2公里。
地球上没有月球，月球的直径约为5公里，但地球上没有月球。
地球上没有月球，月球的直径约为1公里，而月球的直径约为5公里。
地球上的天体有3个月，月球的直径约为1公里。
太阳系中没有月球，月球的直径约为1公里，而月球的直径约为2公里。
地球上没有月球，月球的直径约为1公里。
地球上的月球，月球的直径约为1公里。
地球上的月球，月球的直径约为1公里。
地球上的月球，月球的直径约为1公里。
地球上的月球，月球的直径约为2公里。
地球上的月球，月球的直径约为1公里。

5.145613193511963 s
问题： 二氧化碳的化学分子式是
回答：CO2，CO2是CO2，CO2是CO2，CO，CO2是CO2，CO2是CO2，CO2是CO2，CO2是CO2，CO2是CO2，CO2是CO2，CO2是CO2，CO2是CO2，CO2是CO2，CO2，CO2。
三氧化二锑是二氧化锑，锑是氧化锑。氧化锑是氧化锑，氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。氧化锑是氧化锑。

11.18994688987732 s
问题： 地球上最大的动物是
回答：地球上最大的动物，其实人类最早就在地球上，地球上有许多动物，比如地球上有数百只动物，还有很多动物，这些动物在地球上就有着很多的名字，比如说：天王星、星座、星座、星座、星座、星座等等，但是它们都有很多的种类，如星座、星座、星座、星座等等，它们都是属于人类的。所以地球上任何动物都有它们的身份和地理位置。
地球上有多少个大类：地球上有多少个大类：
地球上有多少个大类：地球上有多少个大类：世界上还有多少个大类：世界上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上的有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：人类的地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上有多少个大类：地球上的还有多少个大小不等的大类。

8.046632289886475 s
问题： 地球自转一圈大约需要
回答：1万亿年时间。
这将是地球上第一个自转的世界，也是地球第一次在地球上进行自转，这次在地球上，将成为人类最早的自转，它将被视为地球的最早的自转，也是人类历史上首次出现的新生命。
这次，地球的自转，将是世界上第一个自转的世界，也是地球上第一个自转的世界，也是人类历史上首次实现自转的人类。

2.332963705062866 s
问题： 杭州市的美食有
回答：哪些？
杭州市的美食有哪些？
杭州市的美食有哪些？
杭州市美的“杭州美食之乡”的美食有：杭州“八大菜系”的美称，杭州市美的“杭州菜系”的美称，杭州“杭州菜系”的美称。
美的“杭州菜系”的美称。
杭州市美的“杭州菜系”的美称。
杭州市美的“杭州菜系”，其特色在于杭州的“杭州菜系”美称。
杭州市美的“杭州菜系”的美称。
杭州的美称。
杭州的美称。
杭州的美称。
杭州的美称。
杭州的美称。
杭州的美称。
杭州的美称。
杭州美食。
杭州的美称。
杭州美称。
杭州的美称。
杭州的美称。
杭州美称。
杭州的美称。
杭州美称。
杭州的美称。
杭州的美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。
杭州美称。

7.825123310089111 s
问题： 江苏省的最好的大学
回答：是江苏省。江苏省是江苏省的最大的大学，是江苏省的最大的大学。江苏省是世界第一个进入世界前五的大学。江苏省的最高学府是南京大学。江苏省是世界第一个进入世界前五的大学。
江苏省的最低学府是江苏省。江苏省的最高学府是南京大学。江苏省的最高学府是南京大学。江苏省的最低学府是南京大学。江苏省的最高学府是南京大学，也是南京大学。江苏省的最高学府是南京大学。
江苏省的最低学府是南京大学。南京大学，位于江苏省的最高学府是南京大学。南京大学也是江苏省唯一一个由省人民政府、中国科学院、南京林业大学、南京林业大学、江苏省人民政府组成的全国重点大学，是江苏省最高学府。南京大学是中国人民解放军和武警部队最高学府之一。
江苏省是江苏省最高学府。南京大学、南京大学，是江苏省最高学府。南京大学。南京大学、南京大学、南京大学。南京大学，南京大学。南京大学。

8.591334819793701 s

**Comment by andeyeluguo** [comment]
我也有复读现象，跑了20轮，只改了batch为256其他没改，不知道为什么这样

**Comment by PshySimon** [comment]
> 我也有复读现象，跑了20轮，只改了batch为256其他没改，不知道为什么这样

我看下面有issue也是类似的，作者说是数据集质量比较低的原因

**Comment by PshySimon** [comment]
不过还想请教作者什么样的数据集算是质量高的呢？预训练对后续微调的影响有多大，如何评估预训练语言模型的好坏呢

**Comment by jingyaogong** [comment]
> 不过还想请教作者什么样的数据集算是质量高的呢？预训练对后续微调的影响有多大，如何评估预训练语言模型的好坏呢

通常来说其他LLM，预训练占到了99%的影响，指令微调只是锦上添花

因为minimind的预训练数据质量不行，所以在sft中尽可能加大学习率，对齐匠数的高质量sft数据。

minimind的pretrain部分是为了跑通「全流程」形式而存在的目前质量不太行，也就是说minimind大部分能力是在sft阶段学到的。我会在之后更新高质量pretrain数据训练后的新模型结果。

**Comment by jingyaogong** [comment]
> 不过还想请教作者什么样的数据集算是质量高的呢？预训练对后续微调的影响有多大，如何评估预训练语言模型的好坏呢

这是现有「序列猴子」的预训练数据：
![image](https://github.com/user-attachments/assets/96f0a27b-66d9-4b2b-9e8f-083c0b727e10)
很明显截图数据包含了太多太多的噪声，人尚且读不懂它一大段在表达什么，训练模型的表现会差的离谱。

这是「BAAI/CCI3-HQ」的预训练数据：
![image](https://github.com/user-attachments/assets/cd68eb37-8534-490a-a26e-f63389cda9b4)
高质量的训练数据是一段表达有始有终有主题的文本，像一个标准的百科全书

可以看一下这相同Billion训练数据的情况下，模型的表现
![image](https://github.com/user-attachments/assets/536ae359-e08e-462f-9cc0-dd4c0f167672)

预训练的数据质量比数据量重要的多，图中都是很不错的开源预训练语料集合，比minimind目前的预训练数据好很多很多很多。

**Comment by PshySimon** [comment]
> > 不过还想请教作者什么样的数据集算是质量高的呢？预训练对后续微调的影响有多大，如何评估预训练语言模型的好坏呢
> 
> 这是现有「序列猴子」的预训练数据： ![image](https://private-user-images.githubusercontent.com/62287848/398307336-96f0a27b-66d9-4b2b-9e8f-083c0b727e10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTM4NjQsIm5iZiI6MTczNTA5MzU2NCwicGF0aCI6Ii82MjI4Nzg0OC8zOTgzMDczMzYtOTZmMGEyN2ItNjZkOS00YjJiLTllOGYtMDgzYzBiNzI3ZTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMjYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjBjZDZmMjcxZjNlMGM5MGFmY2ZhZjQxNjE3ZWIyZmFmY2EyOGQ4ZTJiZDE4OGUyZTJjM2NjMDM4YTVjZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aQi9jzYvI5y47nUSSrEdgjiokko_OB6TwCeNm6F6MdY) 很明显截图数据包含了太多太多的噪声，人尚且读不懂它一大段在表达什么，训练模型的表现会差的离谱。
> 
> 这是「BAAI/CCI3-HQ」的预训练数据： ![image](https://private-user-images.githubusercontent.com/62287848/398307520-cd68eb37-8534-490a-a26e-f63389cda9b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTM4NjQsIm5iZiI6MTczNTA5MzU2NCwicGF0aCI6Ii82MjI4Nzg0OC8zOTgzMDc1MjAtY2Q2OGViMzctODUzNC00OTBhLWEyNmUtZjYzMzg5Y2RhOWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMjYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmQ2OTFhMzU4ZGMyOTIxZGFlYjY4ZTg4ZjljMzhkZGY5MzA1MzVlNmUyNDVjYzMwNWZjMzkyODIwMTk1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yX8xsVYJSERIju8xxKU9z60wEl_CeAZFGoyHXhbe-Ic) 高质量的训练数据是一段表达有始有终有主题的文本，像一个标准的百科全书
> 
> 可以看一下「相同模型 + 相同Billion训练数据」情况下各家数据集的测评结果： ![image](https://private-user-images.githubusercontent.com/62287848/398308177-536ae359-e08e-462f-9cc0-dd4c0f167672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTM4NjQsIm5iZiI6MTczNTA5MzU2NCwicGF0aCI6Ii82MjI4Nzg0OC8zOTgzMDgxNzctNTM2YWUzNTktZTA4ZS00NjJmLTljYzAtZGQ0YzBmMTY3NjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMjYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NDdiMTIxYzliNTcxODg3MDZjMmRmYzY2YzA0MDZkMTE3Yjk5ZGVjZmNlMDUxNWU5NjZkYzc4NDZhMzNkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wFezoXBh81CPAU-_Q1FSERPgmLTbeP1GqBjzYe-v_r4)
> 
> 预训练的数据质量比数据量重要的多，图中都是很不错的开源预训练语料集合，比minimind目前的预训练数据好很多很多很多。

请问这个评测结果是哪一篇论文呢，有可以参考的嘛

**Comment by jingyaogong** [comment]
@PshySimon 
https://arxiv.org/pdf/2410.18505
