### ISSUE TITLE
请问TITAN V*8对0.1B模型pretrain，一个epoch要69小时，这正常嘛？。。。

### ISSUE THREAD

**Issue by CheerfulMinions** [jingyaogong/minimind#102]
如图，8卡吃满了，batch size=18（再大就爆显存了）。
看了很多，感觉TITAN V和2080TI差不了多少，

再慢也不至于69小时啊，流汗。。。

数据集就是那个sft_data_zh.jsonl文件。

<img width="437" alt="{6C0E6C73-ACD0-45BD-B8EE-9CEDEAE0492D}" src="https://github.com/user-attachments/assets/dc8289ca-a361-449d-a112-dd8427aa2506" />

额

<img width="435" alt="{DF867875-F1B7-4BDC-8FAC-B6C440B1DF27}" src="https://github.com/user-attachments/assets/a6bb312f-871a-4331-969f-97e671d2108d" />

配置如下：
<img width="370" alt="{02C3F312-B221-42F4-8F5D-EC611B61B6F8}" src="https://github.com/user-attachments/assets/3b5f118e-cbcf-45d3-8d9e-6f1918026bc6" />

**Comment by CheerfulMinions** [comment]
🆗，我唯一可以想到的是CPU，cpu是e5 2630 v4，可能cpu太拉跨。。。

**Comment by jingyaogong** [comment]
不太正常，你的GPU功率没上去
![image](https://github.com/user-attachments/assets/51a3a1dc-7e43-4f48-b109-e97c2d572cad)
4、50w的功耗，只发挥了1/5
确实是可能cpu和内存不够
