### ISSUE TITLE
dpo_train的多卡训练问题

### ISSUE THREAD

**Issue by VictorSun1996** [jingyaogong/minimind#103]
您好，在使用dpo_train进行训练时，目前已经调通了单卡训练。
在进行多卡训练过程中，进行了如下更改：
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
device = 'cuda'
![1735097676261](https://github.com/user-attachments/assets/757968aa-e965-440e-9ac5-e3bdfb1c198e)

但是确没有运行成功，方便请教一下如何多卡训练吗，万分感谢

**Comment by jingyaogong** [comment]
dpo数据很少单卡够用，没必要分布式训练。另外我手头暂时无法测试，先给出GPT o1的回答，你可以验证一下：

---
---
---
要在单机多卡环境下运行您的训练脚本，您需要进行以下几个步骤。这包括修改代码以支持多GPU训练，并使用适当的启动方式来初始化多GPU训练过程。以下是详细的步骤和代码示例：

## 1. 移除限制使用单个GPU的代码

您的脚本中有一行代码限制了只使用第一个GPU：

```python
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
```

**操作**：删除或注释掉这行代码，以便所有可用的GPU都能被识别和使用。

```python
# os.environ['CUDA_VISIBLE_DEVICES'] = '0'
```

## 2. 确保模型和数据加载支持多GPU

大多数基于 [[Hugging Face Transformers](https://huggingface.co/docs/transformers/index)](https://huggingface.co/docs/transformers/index) 和 [[TRL](https://github.com/lvwerra/trl)](https://github.com/lvwerra/trl) 的训练框架已经内置了对分布式训练的支持。因此，通常不需要手动修改模型或数据加载部分。只需确保模型和数据被正确地移动到对应的设备即可。

### 修改 `init_model` 函数

确保模型被移动到当前设备，而不是硬编码到 `'cuda:0'`。这样，每个进程会自动分配到不同的GPU。

```python
def init_model():
    import torch
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # Do model patching and add fast LoRA weights
    model_name_or_path = "minimind-v1"
    tokenizer_name_or_path = "minimind-v1"
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True)
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name_or_path, trust_remote_code=True, use_fast=False)
    tokenizer.pad_token = tokenizer.eos_token
    model = model.to(device)
    return model, tokenizer
```

## 3. 配置训练参数以支持分布式训练

`TrainingArguments` 需要正确配置以支持多GPU训练。通常，`Trainer` 或 `DPOTrainer` 会自动检测可用的GPU数量并进行相应的设置。

### 修改 `DPOConfig`

确保 `DPOConfig` 中的 `per_device_train_batch_size` 和其他相关参数适应多GPU环境。例如，如果您有 4 个GPU，每个GPU的 `per_device_train_batch_size` 设置为 1，总的批次大小将为 4。

```python
training_config = DPOConfig(
    output_dir="./minimind_dpo",
    per_device_train_batch_size=1,  # 每个GPU上的批次大小
    remove_unused_columns=False,
    report_to="none",
    save_steps=2000,
    learning_rate=4e-5,
    # 其他参数如需要，可以根据需要调整
)
```

## 4. 使用 `torchrun` 启动分布式训练

`torchrun` 是 PyTorch 提供的用于启动分布式训练的工具。假设您有 4 个GPU，可以使用以下命令启动训练：

```bash
torchrun --nproc_per_node=4 your_script.py
```

其中，`your_script.py` 是您的训练脚本文件名。

### 示例

假设您的脚本名为 `train_dpo.py`，并且您有 4 个GPU，启动命令如下：

```bash
torchrun --nproc_per_node=4 train_dpo.py
```

## 5. 完整的修改后脚本示例

以下是根据上述修改后的完整脚本示例：

```python
import os
import warnings
import torch
from transformers import TrainingArguments, AutoModelForCausalLM, AutoTokenizer
from trl import DPOConfig, DPOTrainer
from datasets import load_dataset

warnings.filterwarnings('ignore')

def init_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # Do model patching and add fast LoRA weights
    model_name_or_path = "minimind-v1"
    tokenizer_name_or_path = "minimind-v1"
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True)
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name_or_path, trust_remote_code=True, use_fast=False)
    tokenizer.pad_token = tokenizer.eos_token
    model = model.to(device)
    return model, tokenizer

if __name__ == '__main__':
    model, tokenizer = init_model()
    training_config = DPOConfig(
        output_dir="./minimind_dpo",
        per_device_train_batch_size=1,  # 根据GPU数量调整
        remove_unused_columns=False,
        report_to="none",
        save_steps=2000,
        learning_rate=4e-5,
        # 其他参数可以根据需要添加
    )

    dataset_path = './dataset/dpo/train_data.json'
    train_dataset = load_dataset('json', data_files=dataset_path)

    dpo_trainer = DPOTrainer(
        model=model,
        ref_model=None,
        args=training_config,
        beta=0.1,
        train_dataset=train_dataset['train'],
        tokenizer=tokenizer,
        max_length=512,
        max_prompt_length=512
    )
    dpo_trainer.train()
```

## 6. 验证多GPU是否生效

在训练开始时，您应该能在日志中看到多GPU的信息，例如：

```
Distributed training: True
Number of devices: 4
```

此外，您可以使用 `nvidia-smi` 命令监控每个GPU的使用情况，确保所有GPU都在被充分利用。

## 注意事项

1. **批次大小调整**：在多GPU训练中，通常会根据GPU数量调整总批次大小。例如，如果每个GPU的 `per_device_train_batch_size` 是 1，且有 4 个GPU，总的批次大小就是 4。

2. **梯度累积**：如果由于内存限制无法增加每个GPU的批次大小，可以考虑使用梯度累积。`TrainingArguments` 中的 `gradient_accumulation_steps` 参数可以帮助实现这一点。

3. **随机种子**：确保在分布式训练中设置相同的随机种子，以保证结果的可重复性。

4. **保存和日志**：在分布式训练中，通常只有主进程负责保存模型和记录日志，以避免重复操作。

通过以上步骤，您应该能够在单机多卡环境下顺利运行您的训练脚本，充分利用多GPU的计算能力，提高训练效率。
