### ISSUE TITLE
用numpy实现transformer时, n_heads=16, n_kv_heads=8, 头数不匹配无法矩阵乘法

### ISSUE THREAD

**Issue by 2639823773** [jingyaogong/minimind#104]
![image](https://github.com/user-attachments/assets/ed17cdda-2d4a-46ea-913f-11f1643b1b9d)
计算到这一步的时候, 因为n_heads=16所以说q的head是=16, n_kv_heads=8, 所以k的heads=8导致这里两个heads不一致, 无法矩阵乘法, 要怎么算呢

**Comment by jingyaogong** [comment]
GQA这个问题看这里
https://zhuanlan.zhihu.com/p/645865956
本质上是把kv的heads维度给repeat了
