### ISSUE TITLE
有配套的视频教学吗

### ISSUE THREAD

**Issue by canjian215215** [jingyaogong/minimind#12]

**Comment by jingyaogong** [comment]
[https://www.bilibili.com/video/BV1Ld4fe9EZC/?vd_source=9644e53d7704a3faf52232f7ef91f07e](https://www.bilibili.com/video/BV1Ld4fe9EZC/?vd_source=9644e53d7704a3faf52232f7ef91f07e)

看到了，一直没回，录好再回你。
哈哈
