### ISSUE TITLE
process_seq_monkey 错误

### ISSUE THREAD

**Issue by cts2021** [jingyaogong/minimind#13]
# pretrain
def process_seq_monkey():
    doc_ids = []
    with jsonlines.open('./dataset/mobvoi_seq_monkey_general_open_corpus.jsonl') as reader:
        **for idx, obj in enumerate(reader):**
            content = obj.get('text', '')
            if len(content) > 512:
                continue
            text_id = tokenizer(f'{bos_token}{content}{eos_token}').data['input_ids']
            doc_ids += text_id
            if idx % 50000 == 0:
                print(f"seq_monkey: [{idx}]")

**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 2519: invalid continuation byte**

**Comment by jingyaogong** [comment]
是到文件中间产生的错误，还是一开始就这个Error

**Comment by cts2021** [comment]
文件中间产生的错误，in position 2519。每次都是这个位置。我在 windows 10下处理。

**Comment by jingyaogong** [comment]
不确定是否是文件损坏，可以使用
```bash
md5sum mobvoi_seq_monkey_general_open_corpus.jsonl  # linux
Get-FileHash -Algorithm MD5 mobvoi_seq_monkey_general_open_corpus.jsonl # windows
```
查看这个文件MD5哈希值，应该是`1836f7ba0876bf419b0476bbbb1718fc`，如果不一致可能是文件损坏。

---

我传了一下512长度的分词后的.bin文件

* 其中`pretrain_data_6400.bin`是`data_process.py`第194行
  ```python
  AutoTokenizer.from_pretrained('./model/minimind_tokenizer', use_fast=False) # Line 194
  ```
  使用`./model/minimind_tokenizer`分词器（词表长度6400）的结果


* 其中`pretrain_data_32000.bin`是`data_process.py`第194行
  ```python
  AutoTokenizer.from_pretrained('./model', use_fast=False) # Line 194
  ```
  默认使用mistral分词器（词表长度32000）的结果


对应的修改`./model/LMConfig.py`中的vocab_size为`6400`或者`32000`

[Huggingface-dataset](https://huggingface.co/datasets/jingyaogong/minimind_dataset/tree/main)
[百度网盘](https://pan.baidu.com/s/1-Z8Q37lJD4tOKhyBs1D_6Q?pwd=6666)

**Comment by jingyaogong** [comment]
> 文件中间产生的错误，in position 2519。每次都是这个位置。我在 windows 10下处理。

```python
def process_seq_monkey():
    doc_ids = []
    with jsonlines.open('./dataset/mobvoi_seq_monkey_general_open_corpus.jsonl') as reader:
        for idx, obj in enumerate(reader):
            try:
                content = obj.get('text', '')
                if len(content) > 512:
                    continue
                text_id = tokenizer(f'{bos_token}{content}{eos_token}').data['input_ids']
                doc_ids += text_id
                if idx % 50000 == 0:
                    print(f"seq_monkey: [{idx}]")
            except UnicodeDecodeError as e:
                print(f"Skipping invalid line {idx + 1}: {e}")
                continue

    arr = np.array(doc_ids, dtype=np.uint16)
    with open('./dataset/clean_seq_monkey.bin', 'wb') as f:
        f.write(arr.tobytes())
```

或者试试跳过编码问题的行

**Comment by cts2021** [comment]
好的 谢谢。mobvoi_seq_monkey_general_open_corpus.jsonl  md5 不一致，麻烦给一下mobvoi_seq_monkey_general_open_corpus.jsonl.tar.bz2 的md5.

**Comment by jingyaogong** [comment]
> 好的 谢谢。
> 
> mobvoi_seq_monkey_general_open_corpus.jsonl md5 不一致。
> 
> 麻烦给一下**mobvoi_seq_monkey_general_open_corpus.jsonl.tar.bz2** 的md5.

[seq-monkey官方](https://github.com/mobvoi/seq-monkey-data/blob/main/docs/pretrain_open_corpus.md)给的是`ffacae345d22ab4f1464221d8ecf92c6`。我本地的mobvoi_seq_monkey_general_open_corpus.jsonl.tar.bz2删掉了，再想下100KB/s还是算了。

可以pull一下新的`data_process.py`代码试试是否还会出问题。

如果还是有问题，可以再试试下载我上传[百度网盘](https://pan.baidu.com/s/1Q9BlKzvWmn8xYWNRMP5P8Q?pwd=6666)的`jsonl`文件。这个测试起来是完全正常的。

BWT：动辄30GB+的文件测试起来很困难，被速度卡住了........

谢谢，祝好~

**Comment by cts2021** [comment]
ok
