### ISSUE TITLE
所需硬件

### ISSUE THREAD

**Issue by Godturalmy** [jingyaogong/minimind#19]
请问一下这套模型是否可以部署到嵌入式硬件中，或者像树莓派香橙派这种平台里面，如果可以所需要的内存和硬盘配置这些有要求吗

**Comment by jingyaogong** [comment]
有把7B大小的模型用llama.cpp转成2/4bit量化C++模型`.gguf`可以在8G内存嵌入式设备上运行，可以实现。

* [手把手教你在树莓派4B上运行LLaMA 7B模型](https://mestrace.github.io/posts/2023/Mar/15/llama-rpi/)
* [没错，树莓派5也能飙上Llama 3了！](https://www.jiqizhixin.com/articles/2024-04-23-6)
* [玩转树莓派4B-部署LLM大模型-1](https://www.53ai.com/news/OpenSourceLLM/2024090837528.html)

其实把大模型放到嵌入式设备端侧运行还是希望具备一定生产力、Amazing的聊天效果的。
只不过目前minimind还远远达不到同等能力，所以现在考虑起端侧推理可能没什么目的性，暂无打算。
建议可以基于qwen2-1.8B、phi2-3B这些性能不错的小模型去做量化部署，步骤相对明晰效果也很不错。

祝好~
