### ISSUE TITLE
预训练3轮终止，执行python 0-eval_pretrain.py报错

### ISSUE THREAD

**Issue by SFidea** [jingyaogong/minimind#21]
(glm4) sfidea@DESKTOP-3RVI73I:~/minimind$ python 0-eval_pretrain.py
模型参数: 26.878464 百万 = 0.026878464 B (Billion)
问题： 椭圆和圆的区别
/opt/conda/conda-bld/pytorch_1720538439764/work/aten/src/ATen/native/cuda/Indexing.cu:1231: indexSelectSmallIndex: block: [1,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by jingyaogong** [comment]
不确定，可能是第19行的tokenizer选错了，应该用`'./model/minimind_tokenizer'`不是`'./model'`
```python
tokenizer = AutoTokenizer.from_pretrained('./model/minimind_tokenizer')
```

https://github.com/jingyaogong/minimind/blob/master/0-eval_pretrain.py

如果还是有问题，可以把pretrain完成的.bin权重文件分享，我来试一下

**Comment by SFidea** [comment]
大佬，回复真神速，确实是这个问题，感谢大佬的分享~

**Comment by jingyaogong** [comment]
> 大佬，回复真神速，确实是这个问题，感谢大佬的分享~

OK, 解决就好
no thanks🤝
