### ISSUE TITLE
报错Cannot use apply_chat_template() because tokenizer

### ISSUE THREAD

**Issue by WangRongsheng** [jingyaogong/minimind#27]
您好，

使用了[2-eval.py](https://github.com/jingyaogong/minimind/blob/master/2-eval.py) 推理minimind-218M-Single模型，使用的是mistral的tokenizer，报错：

```
ValueError: Cannot use apply_chat_template() because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating
```

**Comment by jingyaogong** [comment]
> 您好，
> 
> 使用了[2-eval.py](https://github.com/jingyaogong/minimind/blob/master/2-eval.py) 推理minimind-218M-Single模型，使用的是mistral的tokenizer，报错：
> 
> ```
> ValueError: Cannot use apply_chat_template() because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating
> ```

2-eval有修改吗，贴出来看一下呢

**Comment by WangRongsheng** [comment]
```python
import random
import time

import numpy as np
import torch
import warnings
from transformers import AutoTokenizer, AutoModelForCausalLM
from model.model import Transformer
from model.LMConfig import LMConfig

warnings.filterwarnings('ignore')


def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


def init_model(lm_config):
    tokenizer = AutoTokenizer.from_pretrained('./tokenizer_mistral')
    model_from = 1  # 1从权重，2用transformers

    if model_from == 1:
        moe_path = '_moe' if lm_config.use_moe else ''
        ckp = f'./output/full_sft_{lm_config.dim}{moe_path}.pth'

        model = Transformer(lm_config)
        state_dict = torch.load(ckp, map_location=device)

        # 处理不需要的前缀
        unwanted_prefix = '_orig_mod.'
        for k, v in list(state_dict.items()):
            if k.startswith(unwanted_prefix):
                state_dict[k[len(unwanted_prefix):]] = state_dict.pop(k)

        for k, v in list(state_dict.items()):
            if 'mask' in k:
                del state_dict[k]

        # 加载到模型中
        model.load_state_dict(state_dict, strict=False)
    else:
        model = AutoModelForCausalLM.from_pretrained('minimind', trust_remote_code=True)
    
    model = model.to(device)

    print(f'模型参数: {count_parameters(model) / 1e6} 百万 = {count_parameters(model) / 1e9} B (Billion)')
    return model, tokenizer


def setup_seed(seed):
    random.seed(seed)  # 设置 Python 的随机种子
    np.random.seed(seed)  # 设置 NumPy 的随机种子
    torch.manual_seed(seed)  # 设置 PyTorch 的随机种子
    torch.cuda.manual_seed(seed)  # 为当前 GPU 设置随机种子（如果有）
    torch.cuda.manual_seed_all(seed)  # 为所有 GPU 设置随机种子（如果有）
    torch.backends.cudnn.deterministic = True  # 确保每次返回的卷积算法是确定的
    torch.backends.cudnn.benchmark = False  # 关闭 cuDNN 的自动调优，避免不确定性


if __name__ == "__main__":
    # config
    start = ""
    temperature = 0.5
    top_k = 16
    setup_seed(1337)
    # device = 'cpu'
    device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
    dtype = 'bfloat16'
    max_seq_len = 1 * 1024
    lm_config = LMConfig()
    lm_config.max_seq_len = max_seq_len
    # 对话是否携带历史对话（当前模型没有在连续对话数据集上训练，增大历史上文基本不会有新的问答能力）
    contain_history_chat = False

    model, tokenizer = init_model(lm_config)

    model = model.eval()
    # 推送到huggingface
    # model.push_to_hub("minimind")
    # tokenizer.push_to_hub("minimind")

    # answer_way = int(input('输入0自动测试，输入1问题测试：'))
    answer_way = 0
    stream = True

    prompt_datas = [
        '你叫什么名字啊？',
        '你叫什么名字？',
        '中国有哪些比较好的大学？',
        '全世界最好的大学是什么？',
        '你知道光速是多少吗？',
        '你知道长江吗？',
        '人类的血液主要由哪些成分组成？',
        '第一颗人造卫星是哪个国家发射的？',
        '你知道杭州有什么美食吗？',
        '你知道泰山在哪里吗？',
        '地球上最大的动物是什么？',
        '地球自转一圈大约需要多少时间？',
        '人类最早使用的金属是什么？',
        '水的化学分子式是什么？',
        '大气层中含量最多的气体是什么？',
        '世界上最高的山峰是什么？',
        '你知道世界上最深的海沟是什么吗？',
        '最早发明印刷术的是哪个国家？',
        '万有引力是谁提出的？',
        '光合作用的主要原理是什么？',
        '你知道大熊猫的主要食物是什么吗？',
        '海水为什么是咸的？',
        '我们平时喝的牛奶主要含有什么营养成分？',
        '一星期有多少天？'
    ]

    messages_origin = []
    messages = messages_origin

    i = 0
    while i < len(prompt_datas):
        if not contain_history_chat:
            messages = messages_origin.copy()

        if answer_way == 1:
            prompt = input('[Q]: ')
        else:
            prompt = prompt_datas[i]
            print(f'[Q]: {prompt}')
            i += 1

        messages.append({"role": "user", "content": prompt})

        # print(messages)
        new_prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )[-(max_seq_len - 1):]

        x = tokenizer(new_prompt).data['input_ids']
        x = (torch.tensor(x, dtype=torch.long, device=device)[None, ...])

        answer = new_prompt

        with torch.no_grad():
            res_y = model.generate(x, tokenizer.eos_token_id, max_new_tokens=max_seq_len, temperature=temperature,
                                   top_k=top_k, stream=stream)
            print('[A]: ', end='')
            try:
                y = next(res_y)
            except StopIteration:
                print("No answer")
                continue

            history_idx = 0
            while y != None:
                answer = tokenizer.decode(y[0].tolist())
                if answer and answer[-1] == '�':
                    try:
                        y = next(res_y)
                    except:
                        break
                    continue
                # print(answer)
                if not len(answer):
                    try:
                        y = next(res_y)
                    except:
                        break
                    continue

                print(answer[history_idx:], end='', flush=True)
                try:
                    y = next(res_y)
                except:
                    break
                history_idx = len(answer)
                if not stream:
                    break

            print('\n')

        if contain_history_chat:
            assistant_answer = answer.replace(new_prompt, "")
            messages.append({"role": "assistant", "content": assistant_answer})
```

这是代码。

**Comment by jingyaogong** [comment]
确实有问题，tokenizer你用的是./tokenizer_mistral，和我的区别是tokenizer_config.json里没有chat_template聊天模板，可以先把19行改成我的./model测试，看一下区别。

**Comment by WangRongsheng** [comment]
用的https://huggingface.co/mistralai/Mistral-7B-v0.1 这个里面的tokenizer，我正在尝试你提供的

**Comment by WangRongsheng** [comment]
已经解决，使用大佬提供的仓库tokenizer即可，我原本使用的mistral的。

**Comment by WangRongsheng** [comment]
@jingyaogong 请问大佬，mistral的tokenizer应该选择哪个使用？

**Comment by jingyaogong** [comment]
@WangRongsheng 

之前./model/下面放的默认就是Mistral的tokenizer
为了防止歧义，现在就分别放到目录名称下面了
https://github.com/jingyaogong/minimind/tree/master/model/mistral_tokenizer
https://github.com/jingyaogong/minimind/tree/master/model/minimind_tokenizer

**Comment by WangRongsheng** [comment]
你好，

1. 使用 https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-AWQ/blob/main/tokenizer_config.json 中提供的，并且添加chat_template之后，推理都是乱码
![image](https://github.com/user-attachments/assets/c12c6dd8-4e1a-422a-a6a0-cd0056750471)

2. 直接下载提供的https://github.com/jingyaogong/minimind/tree/master/model/mistral_tokenizer 推理正常一些
![image](https://github.com/user-attachments/assets/e19c8ada-221c-4671-b1f1-c6e84524aaac)

请问使用mistral tokenizer除了添加chat_template还有什么其它注意的吗？

**Comment by WangRongsheng** [comment]
暂时通过替换[tokenizer_config.json](https://github.com/jingyaogong/minimind/blob/3732b2d3b5650e3dcf5a9bdbbb142c5415ab6b99/model/tokenizer_config.json) 解决，不是什么大问题。谢谢~

**Comment by jingyaogong** [comment]
> 你好，
> 
> 1. 使用 https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-AWQ/blob/main/tokenizer_config.json 中提供的，并且添加chat_template之后，推理都是乱码
>    ![image](https://private-user-images.githubusercontent.com/55651568/367584821-c12c6dd8-4e1a-422a-a6a0-cd0056750471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgyNTMsIm5iZiI6MTcyNjQwNzk1MywicGF0aCI6Ii81NTY1MTU2OC8zNjc1ODQ4MjEtYzEyYzZkZDgtNGUxYS00MjJhLWE2YTAtY2QwMDU2NzUwNDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMzA4OWUyNGYwNDRkYzJmMGVhN2MxM2VmMGRjODRlN2ExMWYyNDZhNGVkNTdiODI4MGIzMmYzNjAyMDMyZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O7YKotMpzX3e3Ekl7TtXD5voaXhjW6wP97iUIQ_a-rw)
> 2. 直接下载提供的https://github.com/jingyaogong/minimind/tree/master/model/mistral_tokenizer 推理正常一些
>    ![image](https://private-user-images.githubusercontent.com/55651568/367584869-e19c8ada-221c-4671-b1f1-c6e84524aaac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgyNTMsIm5iZiI6MTcyNjQwNzk1MywicGF0aCI6Ii81NTY1MTU2OC8zNjc1ODQ4NjktZTE5YzhhZGEtMjIxYy00NjcxLWIxZjEtYzZlODQ1MjRhYWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNzE3YmJjM2VkOTg2NmIwOGE1ZTkxNzgwZTBjNGU0OWYxZWI4MzhkYmRjZjlkYTZkMzFiMjFhNmI4ZmJmNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m2G62nXB90YKQIMFs1goEM1EJrcWFMp3WTkzilXc3vI)
> 
> 请问使用mistral tokenizer除了添加chat_template还有什么其它注意的吗？

另一个区别就是前几行
```
  "add_bos_token": false,
  "add_eos_token": false,
  "add_prefix_space": true,
```

Mistral：
```
"add_bos_token": true,
"add_eos_token": false,
```

它默认在句子前自动添加<s>起始符，预训练没见过每次 "<s>文本内容" ，输出就不对劲了。

改成前者就行。

**Comment by WangRongsheng** [comment]
ok，谢谢

**Comment by gaojianzhen** [comment]
你好，我在跑推理的时候报相同的错，
执行代码： python eval_llm.py --load_from ./MiniMind2
报错：File "eval_llm.py", line 101, in <module>
    main()
  File "eval_llm.py", line 82, in main
    inputs = tokenizer.apply_chat_template(**templates) if args.weight != 'pretrain' else (tokenizer.bos_token + prompt)
  File "/data_1/xuyiwen/conda/envs/minimind/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1803, in apply_chat_template
    chat_template = self.get_chat_template(chat_template, tools)
  File "/data_1/xuyiwen/conda/envs/minimind/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1967, in get_chat_template
    raise ValueError(
ValueError: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https:
(minimind) 
我没有改过原始代码，请问哪里有问题呢？感谢大佬

**Comment by jingyaogong** [comment]
> 你好，我在跑推理的时候报相同的错， 执行代码： python eval_llm.py --load_from ./MiniMind2 报错：File "eval_llm.py", line 101, in main() File "eval_llm.py", line 82, in main inputs = tokenizer.apply_chat_template(**templates) if args.weight != 'pretrain' else (tokenizer.bos_token + prompt) File "/data_1/xuyiwen/conda/envs/minimind/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1803, in apply_chat_template chat_template = self.get_chat_template(chat_template, tools) File "/data_1/xuyiwen/conda/envs/minimind/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1967, in get_chat_template raise ValueError( ValueError: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https: (minimind) 我没有改过原始代码，请问哪里有问题呢？感谢大佬

@gaojianzhen 

1、检查`MiniMind2`目录是否缺少jinja模版
2、尝试保持 `pip install transformers==4.57.1`

**Comment by gaojianzhen** [comment]
MiniMind2下有chat_template.jinja文件，但是pip install transformers==4.57.1无法下载，目前是4.46.3 报上面的错

<img width="1181" height="244" alt="Image" src="https://github.com/user-attachments/assets/61a1f177-0866-43e7-b0ab-83448822115e" />

**Comment by jingyaogong** [comment]
> pip install transformers==4.57.1

@gaojianzhen `pip install transformers==4.57.1 -i https://mirrors.aliyun.com/pypi/simple/`
