### ISSUE TITLE
关于预训练batch size

### ISSUE THREAD

**Issue by laitselec** [jingyaogong/minimind#30]
尝试复现时看了下预训练的代码，发现似乎没有用梯度累积？ 这样的话每步实际的batch size就只能取非常小了，感觉即使是比较小的模型，大batch size也是必要的吧(比如GPT2-124M每步为0.5M tokens). 在显存比较有限的硬件上，可以通过梯度累积来模拟大batch size.
参考:
[1] https://github.com/karpathy/build-nanogpt (这个是预训练GPT2，我在12GB显存的显卡上复现成功了)
[2] 预训练大模型（不是），关于 batch size 的实验 - Yiliiiii的文章 - 知乎 https://zhuanlan.zhihu.com/p/692260057

**Comment by jingyaogong** [comment]
理论上batchsize越大越好，`1-pretrain.py` 这里默认的batchsize是64，我刚才粗略实验，从64再翻倍的时候，增加 batchsize 能微弱改善loss收敛下限，26M模型最终loss都是收敛在 `3.X` ，大概此时从训练数据中抽样的数据分布到相似瓶颈了，也就是64再往上已经接近匹配真实梯度了，收益微弱，肯定不如 https://zhuanlan.zhihu.com/p/692260057 从`4` 开始算那么巨大。

梯度累积确实也是必要的，比如扩大体积后的模型满足对大batchsize模拟。

https://github.com/jingyaogong/minimind/blob/master/1-pretrain.py 已更新

谢谢支持和交流~
