### ISSUE TITLE
微调需要至少多少条数据？

### ISSUE THREAD

**Issue by charmowen** [jingyaogong/minimind#33]
微调需要至少多少条数据？

**Comment by jingyaogong** [comment]
看目的，全参SFT不用来增加领域知识，这部分理应在PT阶段。

SFT应该是针对某种问法怎么回答，或者下游任务。

Lora-FT是一种外挂，可以不损失原有的回答能力。

但如果要全量SFT的话，需要分阶段混合，比如一开始10%的领域加90的通用，一点点增加到50%的领域（数字是猜的）否则一定会损失基准能力。

此外，如果有百万数据量的话，一个epoch足够了。如果只有几千上万的数据量，可以尝试1~3个epoch，不要太多，容易过拟合。
