### ISSUE TITLE
是否可以发布CPU版，不需要CUDA

### ISSUE THREAD

**Issue by XiNapoleom** [jingyaogong/minimind#35]
现在显卡太贵，是否可以发布不用显卡训练的版本，主要是体验一下训练的整个流程，不注重性能。谢谢

**Comment by jingyaogong** [comment]
默认可以不用GPU，用CPU运行的啊就是速度问题了。
如果只想体验训练流程，可以把
[./model/LMConfig.py](https://github.com/jingyaogong/minimind/blob/master/model/LMConfig.py)
模型继续改得非常小，去训练，比如

```
dim: int = 128,
n_layers: int = 4,
```
可以跑通流程为准

**Comment by sarla999** [comment]
是否可以支持A卡呢，有无相关的资料可以学习。 谢谢

**Comment by WangHHY19931001** [comment]
> 是否可以支持A卡呢，有无相关的资料可以学习。 谢谢

找找微软的dml with pytorch就可以win玩（只要支持dx12的显卡就行），如果要原生amd的话得用linux，不过这两种都得改代码，pytorch的使用特定设备部份需要改改

**Comment by chuanzhubin** [comment]
> 默认可以不用GPU，用CPU运行的啊，就是速度问题了。 如果只想体验训练流程，可以把 [./model/LMConfig.py](https://github.com/jingyaogong/minimind/blob/master/model/LMConfig.py) 模型继续改得非常小，去训练，比如
> 
> ```
> dim: int = 128,
> n_layers: int = 4,
> ```
> 
> 可以跑通流程为准

如果想要模型变小，除了这两个参数，还可以动哪些参数？

**Comment by chuanzhubin** [comment]
感谢！

**Comment by jingyaogong** [comment]
> > > 默认可以不用GPU，用CPU运行的啊，就是速度问题了。 如果只想体验训练流程，可以把 [./model/LMConfig.py](https://github.com/jingyaogong/minimind/blob/master/model/LMConfig.py) 模型继续改得非常小，去训练，比如
> > > ```
> > > dim: int = 128,
> > > n_layers: int = 4,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 可以跑通流程为准
> > 
> > 
> > 如果想要模型变小，除了这两个参数，还可以动哪些参数？
> 
> @chuanzhubin
> 
> ```
> 参数数量: 26.88 百万 
> 模块: embeddings, 参数数量: 3.28 百万 
> 模块: dropout, 参数数量: 0.00 百万 
> 模块: layers * 8, 参数数量: 23.60 百万
> 模块: layers.0, 参数数量: 2.95 百万 
> 模块: layers.0.attention, 参数数量: 0.79 百万 
> 模块: layers.0.attention.wq, 参数数量: 0.26 百万 
> 模块: layers.0.attention.wk, 参数数量: 0.13 百万 
> 模块: layers.0.attention.wv, 参数数量: 0.13 百万 
> 模块: layers.0.attention.wo, 参数数量: 0.26 百万 
> 模块: layers.0.attention.attn_dropout, 参数数量: 0.00 百万 
> 模块: layers.0.attention.resid_dropout, 参数数量: 0.00 百万 
> 模块: layers.0.attention_norm, 参数数量: 0.00 百万 
> 模块: layers.0.ffn_norm, 参数数量: 0.00 百万 
> 模块: layers.0.feed_forward, 参数数量: 2.16 百万 
> 模块: layers.0.feed_forward.w1, 参数数量: 0.72 百万 
> 模块: layers.0.feed_forward.w2, 参数数量: 0.72 百万 
> 模块: layers.0.feed_forward.w3, 参数数量: 0.72 百万 
> 模块: layers.0.feed_forward.dropout, 参数数量: 0.00 百万 
> 模块: norm, 参数数量: 0.00 百万 
> 模块: output, 参数数量: 3.28 百万 
> ```
> 
> #### Transformer-Decoder模型参数来自哪些
> 26.88M的模型
> 
> * 来自于词嵌入和词解码线性层，这俩是共享参数的，目前Linear(512->6400) 只占了3.28M（参数占比 12.2%）
> * attention投影层占了6.32M（参数占比 23.51%）
> * ffn占了大半江山17.28M（参数占比 64.29%）
> 
> #### 超参调整
> * token_dim=512，block layers=8，这两个地方调整会直接影响到ffn线性层和隐藏层参数数量和attention投影的维度。
> * 如果想压缩词表长度，vocab_size从6400再减几乎没什么参数收益，且6400已经很小了。
> * n_heads和n_kv_heads的设置不影响参数量，多头的dimension已经被dim//头数算出来了。
> * multiple_of也不用管了，这个用来找8的最近倍数优化内存访问用的，也几乎不影响。
> 
> 综上，需要模型变大变小 ≈ 只需要调整 `dim` 和 `layers` 就可以了。
> 
> 以上讨论并非minimind独有，对于其它所有LLM（llama系列、qwen系列、mistral系列、yi系列、gpt系列......）只要大的架构类似，都是适用的。

**Comment by yukaichao** [comment]
> 是否可以支持A卡呢，有无相关的资料可以学习。 谢谢

https://github.com/yukaichao/minimind_AMD_ROCM
我修改一些脚本后可以训练和测试了，你可以参考下。
