### ISSUE TITLE
实现 Mamba + Transformer 新架构

### ISSUE THREAD

**Issue by WangRongsheng** [jingyaogong/minimind#37]
大佬可以看一下新架构的LLM，可以集成做一个小的实现：

1. https://github.com/kyegomez/Jamba

**Comment by jingyaogong** [comment]
Mamba系列和RWKV这种线性推理复杂度结构其实有尝试过加入，参考：

[mamba.zip](https://github.com/user-attachments/files/17071753/mamba.zip)

这个是简单集成mamba到minimind的实现。`./model/mamba.py` 里面状态空间模型(SSM)在 `selective_scan` 函数逐步对输入序列进行处理。每一步都依赖前一步的状态更新，并行计算效率很慢。
```
 for i in range(l):
      x = deltaA[:, i] * x + deltaB_u[:, i]
      y = einsum(x, C[:, i, :], 'b d_in n, b n -> b d_in')
      ys.append(y)
```
速度问题主要来自这里，这种是顺序循环的，官方mamba代码做了并行加速处理（具体快多少倍不得而知没试过），状态空间模型参数A,B,C,D离散化（einsum）同时计算多时间步的数据，尽管SSM状态更新本身是递归的。

粗略试了一下现在这种16M参数的mamba训练时间是26M transformer模型10倍+，所以之前暂时放弃对mamba的尝试了

Jamba这种把mambablock替换transformer attention挺好，但是 https://github.com/kyegomez/Jamba 给的库文件好像不是很全。huggingface官方的Jamba 足足2000行代码集成（阅读恐惧症，暂时搁置）：https://github.com/huggingface/transformers/blob/main/src/transformers/models/jamba/modeling_jamba.py

**Comment by WangRongsheng** [comment]
谢谢解答，很棒的尝试~
