### ISSUE TITLE
tokenizer训练数据集

### ISSUE THREAD

**Issue by leonno10** [jingyaogong/minimind#4]
您好，非常感谢作者大神的开源，请问一下训练tokenizer的训练数据集可以提供一下吗？

**Comment by jingyaogong** [comment]
okay，确实忘记上传了

[huggingface下载地址](https://huggingface.co/datasets/jingyaogong/minimind_dataset/tree/main)

[百度网盘下载地址](https://pan.baidu.com/s/1yAw1LVTftuhQGAC1Y9RdYQ?pwd=6666)

不过tokenizer训练集用什么不是那么重要，这个是我用sft数据集简单清洗整理出来的。

**Comment by leonno10** [comment]
感谢大佬
