### ISSUE TITLE
原1-pretrain.py的dtype改成b或者bfloat1666666也能正常训练呢

### ISSUE THREAD

**Issue by cqcracked** [jingyaogong/minimind#45]
如题

**Comment by jingyaogong** [comment]
对的，一个小错误，没主意😂
```python
scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype == args.dtype))
```
->
```python
scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype in ['float16', 'bfloat16']))
```

感谢指出

**Comment by cqcracked** [comment]
你好！
&nbsp;你的minimind项目很有意义，学到很多。谢谢，这里有2个问题想请教一下：
&nbsp;一。&nbsp; 0-eval_pretrain.py、1-pretrain.py、2-eval.py、3-full_sft.py 执行都没有问题（知道了0-1的过程）
train_tokenizer.py 也能看明白。但是在我执行4-lora_sft.py的时候，发现模型的加载方式同3-full_sft.py有很大的不同
4里面模型加载是用的model = AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True).to(args.device)
minimind-v1-small目录（这个应该https://www.modelscope.cn/models/gongjy/MiniMind-V1）下面就多了很多json文件，请问为什么这里同3-full_sft.py 加载模型的方式不同。3这种方式每一步都清楚，4-lora_sft.py这里加载就多了很多json文件，并且模型名称也突然变为了pytorch_model.bin&nbsp; 因为这个项目是0-1，所以还是想知道整个过程。
二。4-lora_sft.py 中&nbsp; model_name_or_path = "./out/full_sft_512.pth"就无法启动程序了,说是缺少json文件


谢谢







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyaogong/minimind"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月25日(星期三) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyaogong/minimind] 原1-pretrain.py的dtype改成b或者bfloat1666666也能正常训练呢 (Issue #45)






对的，一个小错误，没主意😂
scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype == args.dtype))

-&gt;
scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype in ['float16', 'bfloat16']))

感谢指出

**Comment by jingyaogong** [comment]
> 你好！ &nbsp;你的minimind项目很有意义，学到很多。谢谢，这里有2个问题想请教一下： &nbsp;一。&nbsp; 0-eval_pretrain.py、1-pretrain.py、2-eval.py、3-full_sft.py 执行都没有问题（知道了0-1的过程） train_tokenizer.py 也能看明白。但是在我执行4-lora_sft.py的时候，发现模型的加载方式同3-full_sft.py有很大的不同 4里面模型加载是用的model = AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True).to(args.device) minimind-v1-small目录（这个应该[https://www.modelscope.cn/models/gongjy/MiniMind-V1）下面就多了很多json文件，请问为什么这里同3-full_sft.py](https://www.modelscope.cn/models/gongjy/MiniMind-V1%EF%BC%89%E4%B8%8B%E9%9D%A2%E5%B0%B1%E5%A4%9A%E4%BA%86%E5%BE%88%E5%A4%9Ajson%E6%96%87%E4%BB%B6%EF%BC%8C%E8%AF%B7%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E9%87%8C%E5%90%8C3-full_sft.py) 加载模型的方式不同。3这种方式每一步都清楚，4-lora_sft.py这里加载就多了很多json文件，并且模型名称也突然变为了pytorch_model.bin&nbsp; 因为这个项目是0-1，所以还是想知道整个过程。 二。4-lora_sft.py 中&nbsp; model_name_or_path = "./out/full_sft_512.pth"就无法启动程序了,说是缺少json文件 谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jingyaogong/minimind" ***@***.***&gt;; 发送时间:&nbsp;2024年9月25日(星期三) 上午10:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jingyaogong/minimind] 原1-pretrain.py的dtype改成b或者bfloat1666666也能正常训练呢 (Issue #45) 对的，一个小错误，没主意😂 scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype == args.dtype)) -&gt; scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype in ['float16', 'bfloat16'])) 感谢指出 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


`minimind-v1-small` 完整的文件在这里
```bash
git clone https://huggingface.co/jingyaogong/minimind-v1-small
```
pretrain和full_sft都是原生pytorch训练的，常规加载.pth权重，所以确实是清晰的

lora层的初始化用的是peft库，只需要很方便的定义一下
```
peft_config=LoraConfig(<参数>)
```
把Lora低秩矩阵的参数一填，再通过
```
model = get_peft_model(model, peft_config)
```
就自动可以在原有model基础上附加Lora层权重参与训练了（model参数自动被冻结），非常省事~

---
省事的前提是，peft需要配合transformers库一起使用

所以执行lora-sft需要提前把原生pytorch模型权重导出成transformers格式，保存到一个文件夹里
文件夹内包含自定义Transformer模型的model_config，权重.pth，模型代码，generation_config.json......等等文件，这是一个模型可以运行的（最小且完整的）五脏六腑（transformers模型格式）

导出transformers模型的方式很简单，参考[./export_model.py](https://github.com/jingyaogong/minimind/blob/master/export_model.py)

**Comment by cqcracked** [comment]
明白了，感谢，持续关注。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyaogong/minimind"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月25日(星期三) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyaogong/minimind] 原1-pretrain.py的dtype改成b或者bfloat1666666也能正常训练呢 (Issue #45)






你好！ &nbsp;你的minimind项目很有意义，学到很多。谢谢，这里有2个问题想请教一下： &nbsp;一。&nbsp; 0-eval_pretrain.py、1-pretrain.py、2-eval.py、3-full_sft.py 执行都没有问题（知道了0-1的过程） train_tokenizer.py 也能看明白。但是在我执行4-lora_sft.py的时候，发现模型的加载方式同3-full_sft.py有很大的不同 4里面模型加载是用的model = AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True).to(args.device) minimind-v1-small目录（这个应该https://www.modelscope.cn/models/gongjy/MiniMind-V1）下面就多了很多json文件，请问为什么这里同3-full_sft.py 加载模型的方式不同。3这种方式每一步都清楚，4-lora_sft.py这里加载就多了很多json文件，并且模型名称也突然变为了pytorch_model.bin&nbsp; 因为这个项目是0-1，所以还是想知道整个过程。 二。4-lora_sft.py 中&nbsp; model_name_or_path = "./out/full_sft_512.pth"就无法启动程序了,说是缺少json文件 谢谢
…
------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jingyaogong/minimind" @.&gt;; 发送时间:&nbsp;2024年9月25日(星期三) 上午10:11 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jingyaogong/minimind] 原1-pretrain.py的dtype改成b或者bfloat1666666也能正常训练呢 (Issue #45) 对的，一个小错误，没主意😂 scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype == args.dtype)) -&gt; scaler = torch.cuda.amp.GradScaler(enabled=(args.dtype in ['float16', 'bfloat16'])) 感谢指出 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;

minimind-v1-small 完整的文件在这里
git clone https://huggingface.co/jingyaogong/minimind-v1-small

pretrain和full_sft都是原生pytorch训练的，常规加载.pth权重，所以确实是清晰的

lora层的初始化用的是peft库，只需要很方便的定义一下
peft_config=LoraConfig(<参数&gt;)
把Lora低秩矩阵的参数一填，再通过
model = get_peft_model(model, peft_config)
就自动可以在原有model基础上附加Lora层权重参与训练了（model参数自动被冻结），非常省事~


省事的前提是，peft需要配合transformers库一起使用

所以执行lora-sft需要提前把原生pytorch模型权重导出成transformers格式，保存到一个文件夹里
文件夹内包含自定义Transformer模型的model_config，权重.pth，模型代码，generation_config.json......等等文件，这是一个模型可以运行的（最小且完整的）五脏六腑（transformers模型格式）

导出transformers模型的方式很简单，参考./export_model.py
