### ISSUE TITLE
邮件回复

### ISSUE THREAD

**Issue by iomgaa-ycz** [jingyaogong/minimind#46]
您好，尊敬的MiniMind所有者，我已经向您的邮箱gongjy.cs@gmail.com发送了关于Accelerate的邮件，非常期待您的回复。

**Comment by jingyaogong** [comment]
453***883@qq.com是你吗
如果不是，可能gmail丢邮件了，没有发现其它邮件，可以发到gongjy.cs@qq.com重新联系我
如果是，我马上回复

**Comment by iomgaa-ycz** [comment]
453***883@qq.com并不是我的邮箱，我是一个gmail邮箱。现已经重新向[gongjy.cs@qq.com](mailto:gongjy.cs@qq.com)发送了邮件。
