### ISSUE TITLE
moe模型是否更难训

### ISSUE THREAD

**Issue by WangRongsheng** [jingyaogong/minimind#47]
您好，

最近我一直在更大的pre-train数据集上做一些测试训练LLM的工作，我发现MoE模型更难被训练，我是使用了仓库中给的moe模型进行测试，效果也是不太好。

**Comment by jingyaogong** [comment]
是这样的
每个FFN作为一个专家（不考虑share_expert的话）
如果设定4个专家，相同的语料，相当于每个FFN只有原本1/4被路由到的概率得到训练
至少需要跑更多的epoch确保每个FFN保证和dense模型得到一样多的学习
简单的直觉是moe需要原本epoch x 4，或者扩大 x 4 倍的训练集
需要实验经验主义来确定了

感谢持续关注~~~

**Comment by jingyaogong** [comment]
> 您好，
> 
> 最近我一直在更大的pre-train数据集上做一些测试训练LLM的工作，我发现MoE模型更难被训练，我是使用了仓库中给的moe模型进行测试，效果也是不太好。

另外pretrain效果不太好，可以参考
https://github.com/jingyaogong/minimind/issues/23

这个问题目前改成存到csv文件，一整个text作为一次语料，不进行交叉拼接了，提示上下文的一致性。

可以pull一下最新的data_process处理出csv文件，试试新的pretrain过程效果是否有增进

**Comment by WangRongsheng** [comment]
okok，谢谢！

**Comment by jingyaogong** [comment]
> > 您好，
> > 最近我一直在更大的pre-train数据集上做一些测试训练LLM的工作，我发现MoE模型更难被训练，我是使用了仓库中给的moe模型进行测试，效果也是不太好。
> 
> 另外pretrain效果不太好，可以参考 #23
> 
> 这个问题目前改成存到csv文件，一整个text作为一次语料，不进行交叉拼接了，改进上下文的一致性。 因为对于小模型小max_len的做法，这种交叉上下文造成胡言乱语比较严重，不能和大模型预训练一视同仁。
> 
> 可以pull一下最新的data_process处理出csv文件，试试新的pretrain过程效果，会有一定增进


@WangRongsheng 测试了一下新的pretrain方式反而有点问题，输出存在严重的【复读机】现象，在想办法Fix。暂时不要更新了吧😂
