### ISSUE TITLE
1-pretrain中新增的loss mask与现有F.cross_entropy参数不匹配问题

### ISSUE THREAD

**Issue by lesterlee89** [jingyaogong/minimind#51]
1.如题，作者新加的mask处理不足一个max_len的情况下的loss计算问题，但model.py计算loss还是reduce模式，这个loss计算出来已经是一个标量了，后续mask就无效了，
2.是不是可以将F.cross_entropy增加上（size_average=False, reduce=False）这两参数

**Comment by jingyaogong** [comment]
是的，完全正确，不加, reduction='none' 的话它直接返回一个平均标量损失，已更新bug

谢谢你的细心发现！！！
