### ISSUE TITLE
5-dpo_train.py的问题

### ISSUE THREAD

**Issue by cqcracked** [jingyaogong/minimind#53]
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
device = 'cuda:0'

这2行0改为1 就出错了。
但实际上我执行torchrun --nproc_per_node 2 3-full_sft.py  并没有问题。

报错信息：RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by jingyaogong** [comment]
![image](https://github.com/user-attachments/assets/72d76e48-f19e-4a28-bd46-10c3170cbb94)

```
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
device = 'cuda:0'
```
所以应该这么填
