### ISSUE TITLE
hidden_dim = 4 * dim 设置原因

### ISSUE THREAD

**Issue by pengqianhan** [jingyaogong/minimind#61]
model/model.py 中的第 141 行 ‘‘hidden_dim = 4 * dim’’ 请问hidden_dim 这么设置的原因是什么呢。希望大佬可以解答一下，非常感谢。

**Comment by jingyaogong** [comment]
> model/model.py 中的第 141 行 ‘‘hidden_dim = 4 * dim’’ 请问hidden_dim 这么设置的原因是什么呢。希望大佬可以解答一下，非常感谢。

如果需要知道 `n * dim` 的 `n` 为什么设置成 `4` 而不是其它数字

其实最初的[Transformer论文(Vaswani et al., 2017)](https://proceedings.neurips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf)中，作者 4 * dim 作为FFN隐藏层维度，后面心照不宣都是用4了，包括现在的[llama3](https://github.com/meta-llama/llama3/blob/main/llama/model.py)：
![image](https://github.com/user-attachments/assets/2822e8f7-1fbd-4fdf-9033-088855789824)

至于 `n` 取多少，可以自由定义，没有严格限制
隐藏层需要比dim本身大，可以增加模型的容量（即模型的表达能力）。

* 大脑的思考过程也是一样：人类每听1个字+说1个字，流入流出的信息虽然很少。但是这些字在大脑内部却经历了o(N)复杂度的隐藏计算，N需要更大，表达能力才能更强。

  ```
  人类听1个字 -> 【人类大脑在hidden_dim=N计算M次】 -> 人类说1个字
  ```

* 对应到这里的token

  ```
  输入dim=512维度 -> 【模型大脑在hidden_dim=dim*n维度计算】 -> 输出dim=512维度
  ```

理论上隐藏层越大越好。隐藏层太小，表达能力会受限；但太大计算成本会显著增加。大模型参数体积就主要来自于FFN的隐藏层，具体可以看这个[issue comment](https://github.com/jingyaogong/minimind/issues/35#issuecomment-2374016027)的分析。


总结而言
1、4是约定俗成，默认用4，但可以自由更改（只要取得效果和参数体积的平衡即可）
2、扩大 `n*dim` 的原因就是需要获得【更强的表达能力】

有其它任何问题欢迎继续交流~

**Comment by jingyaogong** [comment]
> > model/model.py 中的第 141 行 ‘‘hidden_dim = 4 * dim’’ 请问hidden_dim 这么设置的原因是什么呢。希望大佬可以解答一下，非常感谢。
> 
> 如果需要知道 `n * dim` 的 `n` 为什么设置成 `4` 而不是其它数字
> 
> 其实最初的[Transformer论文(Vaswani et al., 2017)](https://proceedings.neurips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf)中，作者 4 * dim 作为FFN隐藏层维度，后面心照不宣都是用4了，包括现在的[llama3](https://github.com/meta-llama/llama3/blob/main/llama/model.py)： ![image](https://private-user-images.githubusercontent.com/62287848/374776003-2822e8f7-1fbd-4fdf-9033-088855789824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDIyNDIsIm5iZiI6MTcyODQ0MTk0MiwicGF0aCI6Ii82MjI4Nzg0OC8zNzQ3NzYwMDMtMjgyMmU4ZjctMWZiZC00ZmRmLTkwMzMtMDg4ODU1Nzg5ODI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAyNDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWVhMzNlMTA3YzJkNTliMWFkMTM0MDA1OGI5ZDJkMmQwZjU4YjBmMzc0MWVhY2ViNzlmYWE0MmE3YWU5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wizhXd9yDOyMw9jlsfCzQIh6y6RE9XGYlTpkMcVIiy8)
> 
> 至于 `n` 取多少，可以自由定义，没有严格限制 隐藏层需要比dim本身大，可以增加模型的容量（即模型的表达能力）。
> 
> * 大脑的思考过程也是一样：人类每听1个字+说1个字，流入流出的信息虽然很少。但是这些字在大脑内部却经历了o(N)复杂度的隐藏计算，N需要更大，表达能力才能更强。
>   ```
>   人类听1个字 -> 【人类大脑在hidden_dim=N计算M次】 -> 人类说1个字
>   ```
> * 对应到这里的token
>   ```
>   输入dim=512维度 -> 【模型大脑在hidden_dim=dim*n维度计算】 -> 输出dim=512维度
>   ```
> 
> 理论上隐藏层越大越好。隐藏层太小，表达能力会受限；但太大计算成本会显著增加。大模型参数体积就主要来自于FFN的隐藏层，具体可以看这个[issue comment](https://github.com/jingyaogong/minimind/issues/35#issuecomment-2374016027)的分析。
> 
> 总结而言 1、4是约定俗成，默认用4，但可以自由更改（只要取得效果和参数体积的平衡即可） 2、扩大 `n*dim` 的原因就是需要获得【更强的表达能力】
> 
> 有其它任何问题欢迎继续交流~
