### ISSUE TITLE
DPO数据处理为空

### ISSUE THREAD

**Issue by lesterlee89** [jingyaogong/minimind#65]
https://github.com/jingyaogong/minimind/blob/36fadc7ef1e83dab0fe56efd075e82e48ede624b/data_process.py#L123
使用数据预处理脚本中默认代码处理那三个json文件，最后生成的reject和chosen项都为空，正常处理后生成的dpo训练数据应该是什么样的，作则方便给个截图看下吗，

**Comment by jingyaogong** [comment]
> https://github.com/jingyaogong/minimind/blob/36fadc7ef1e83dab0fe56efd075e82e48ede624b/data_process.py#L123
> 
> 
> 使用数据预处理脚本中默认代码处理那三个json文件，最后生成的reject和chosen项都为空，正常处理后生成的dpo训练数据应该是什么样的，作则方便给个截图看下吗，

更新了代码，pull一下最新的即可
训练数据和三个json文件保持一致格式

**Comment by lesterlee89** [comment]
谢谢
