### ISSUE TITLE
请问如何微调不同size的模型

### ISSUE THREAD

**Issue by luckyfan-cs** [jingyaogong/minimind#66]
有什么size设置的方法吗

**Comment by jingyaogong** [comment]
model/LMConfig.py

512+8代表26M
768+16代表108M

**Comment by luckyfan-cs** [comment]
感谢回复，请问怎么自定义模型的size,比如从 50M，100M,500M, 1B,2B 到超过 7B 参数。有什么好的参数设置的方法吗

**Comment by jingyaogong** [comment]
> 感谢回复，请问怎么自定义模型的size,比如从 50M，100M,500M, 1B,2B 到超过 7B 参数。有什么好的参数设置的方法吗

![image](https://github.com/user-attachments/assets/4b2ccc48-be07-47e8-bacd-0c525c55bc4b)

参考GPT3
