### ISSUE TITLE
768爆显存

### ISSUE THREAD

**Issue by yhl41001** [jingyaogong/minimind#67]
使用两个A800（80G）训练768的模型，在加载数据的时候，经常出现爆显存的问题，偶尔不报能正常训练起来，只占30G显存，不知道这个问题有没有遇到过，如何解决？

**Comment by jingyaogong** [comment]
没有遇到过，有没有更多可参考的日志或其他信息。

另外模型是768*16

还是768*16*N的MoE

**Comment by yhl41001** [comment]
模型是768*16，我观察到了显存增长超出显卡的显存了。

**Comment by jingyaogong** [comment]
> 模型是768*16，我观察到了显存增长超出显卡的显存了。

`max_seq_len` 有没有改过

降低 `batch_size` 直到可以运行

**Comment by yhl41001** [comment]
> > 模型是768*16，我观察到了显存增长超出显卡的显存了。
> 
> `max_seq_len` 有没有改过
> 
> 降低 `batch_size` 直到可以运行

这两个都没改过，现在模型在训练，等训练玩了我有时间看一下是怎么回事！
