### ISSUE TITLE
结果复现效果问题

### ISSUE THREAD

**Issue by lesterlee89** [jingyaogong/minimind#68]
1.使用大佬说明里的预训练、SFT数据，完全按照文档说明进行训练，只不过用的是8卡
2.超参数都按代码默认的，训练完用2-eval测试同样的问题，自己训练的full_sft模型比作者效果要差不少，
请问有可能是什么原因导致的
![20241016180518](https://github.com/user-attachments/assets/cf56e5e3-9251-45be-906e-2b29b55cb27b)

**Comment by jingyaogong** [comment]
pretrain，sft分别进行了几轮

**Comment by lesterlee89** [comment]
都是5轮

**Comment by jingyaogong** [comment]
> 1.都是5轮 2.学习率都是1e-4 3.batch分别是64 32

可以测一下 `0-eval-pretrain.py` 的模型接龙效果

seq-monkey的pretrain数据集质量一般（不宜多炼）
相反，匠数sft的数据集质量很高且足够大，这一点和其它大模型不同。

没记错的话，我release出来的是pretrain 2轮+sft 10轮的模型结果

现在你可以在sft阶段把学习率增加到1.5e-4
```python
# 113行
ckp = f'./out/pretrain_{lm_config.dim}{moe_path}.pth'
# 改成
ckp = f'./out/full_sft_{lm_config.dim}{moe_path}.pth'
```
加载现在的sft模型，再跑5~10轮，看一下效果

> 对了，模型是默认的 (512+8) 26.88M大小吗？

**Comment by lesterlee89** [comment]
1.接龙效果也不好
2.我用自己的sft模型再多迭代5轮看看
3.对，模型用的是26.88的

| |
lesterlee2014
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月16日 22:58 |
| 收件人 | jingyaogong/minimind ***@***.***> |
| 抄送人 | lesterlee89 ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [jingyaogong/minimind] 结果复现效果问题 (Issue #68) |

1.都是5轮 2.学习率都是1e-4 3.batch分别是64 32

@lesterlee89

可以测一下 0-eval-pretrain.py 的模型接龙效果

seq-monkey的pretrain数据集质量一般（不宜多炼）

相反，匠数sft的数据集质量很高且足够大，这一点和其它大模型不同。

没记错的话，我release出来的是pretrain 2轮+sft 10轮的模型结果

现在你可以在sft阶段把学习率增加到1.5e-4

# 113行ckp=f'./out/pretrain_{lm_config.dim}{moe_path}.pth'# 改成ckp=f'./out/full_sft_{lm_config.dim}{moe_path}.pth'

加载现在的sft模型，再跑5~10轮，看一下效果

对了，模型是默认的 (512+8) 26.88M大小吗？

**Comment by jingyaogong** [comment]
> 1.接龙效果也不好 2.我用自己的sft模型再多迭代5轮看看 3.对，模型用的是26.88的

好的 @lesterlee89 
完成后的最新的效果，若方便，随时更新到Comment

**Comment by Sure0520** [comment]
> 1.接龙效果也不好 2.我用自己的sft模型再多迭代5轮看看 3.对，模型用的是26.88的

请问sft模型多迭代之后效果如何？

**Comment by lesterlee89** [comment]
1.效果未复现是我的处理后sft数据不完整，从作者给的sft官网下载后的数据用data_process脚本处理提示有_csv.Error: need to escape, but no escapechar set错误，在df.to_csv函数增加 escapechar='|' 或者 escapechar='\\' 可以解决报错，但提取后的sft数据不完整。导致在sft模型再多迭代8次也没有效果提升。

2.使用作者处理后的sft完整数据，按作者推荐的pretrain 2轮，sft 10轮从新训练，可以复现效果。

3.这里提一点，在sft阶段，我5-10轮都在有观察效果，发现还是迭代轮数越多，sft效果越好

**Comment by Sure0520** [comment]
> 1.效果未复现是我的处理后sft数据不完整，从作者给的sft官网下载后的数据用data_process脚本处理提示有_csv.Error: need to escape, but no escapechar set错误，在df.to_csv函数增加 escapechar='|' 或者 escapechar='\' 可以解决报错，但提取后的sft数据不完整。导致在sft模型再多迭代8次也没有效果提升。
> 
> 2.使用作者处理后的sft完整数据，按作者推荐的pretrain 2轮，sft 10轮从新训练，可以复现效果。
> 
> 3.这里提一点，在sft阶段，我5-10轮都在有观察效果，发现还是迭代轮数越多，sft效果越好

非常感谢回答！

**Comment by jingyaogong** [comment]
> 1.效果未复现是我的处理后sft数据不完整，从作者给的sft官网下载后的数据用data_process脚本处理提示有_csv.Error: need to escape, but no escapechar set错误，在df.to_csv函数增加 escapechar='|' 或者 escapechar='\' 可以解决报错，但提取后的sft数据不完整。导致在sft模型再多迭代8次也没有效果提升。
> 
> 2.使用作者处理后的sft完整数据，按作者推荐的pretrain 2轮，sft 10轮从新训练，可以复现效果。
> 
> 3.这里提一点，在sft阶段，我5-10轮都在有观察效果，发现还是迭代轮数越多，sft效果越好

![image](https://github.com/user-attachments/assets/98dd985c-11a0-4d96-afbc-e7734b564c02)
提醒到我了，是因为这里默认限制中文占比>0.9，解析出来用于训练的数据你那边应该只有500M
我放出来的 `sft_data_single.csv` 应该是是0.86下洗出来的，大约1.82GB
限制再松一些，训练数据更多效果会更好

**Comment by lesterlee89** [comment]
@ @jingyaogong 谢谢
