### ISSUE TITLE
模型的输入输出长度

### ISSUE THREAD

**Issue by cqcracked** [jingyaogong/minimind#69]
1.这个模型训练好后，上下文输入的长度最长能到多少，是由max_seq_len: int = 512 来控制的吗？
2.这个模型训练好后，输出的最大长度是由哪里控制的呢？谢谢

**Comment by jingyaogong** [comment]
> 1.这个模型训练好后，上下文输入的长度最长能到多少，是由max_seq_len: int = 512 来控制的吗？
> 2.这个模型训练好后，输出的最大长度是由哪里控制的呢？谢谢

是的由它决定

**Comment by cqcracked** [comment]
谢谢，我看了下代码，minimind比较清楚了。其它大模型的输入输出长度也是这么直接限制吗？麻烦解释一下呢？话说rope也有外推能力呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyaogong/minimind"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月17日(星期四) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyaogong/minimind] 模型的输入输出长度 (Issue #69)





  
1.这个模型训练好后，上下文输入的长度最长能到多少，是由max_seq_len: int = 512 来控制的吗？
 2.这个模型训练好后，输出的最大长度是由哪里控制的呢？谢谢
  
是的由它决定

**Comment by jingyaogong** [comment]
max_seq_len只起到截断作用，具体从哪截 ，怎么截，截多少都不重要，只是为了模型性能服务罢了。设置到10000万也没任何关系，输入输出反正'不会报错'。

输入太长影响的是：模型训练只见过的512以内编码长度，以外的文本在训练之外，从没见过，性能会大打折扣罢了。rope靠插值做长度外推，缓解这种影响而已。

「外不外推」影响的是质量

和你问题「怎样限制输入输出长度」本身没有任何关系。
