### ISSUE TITLE
效果不太好哦~~~

### ISSUE THREAD

**Issue by luofeng0603** [jingyaogong/minimind#7]
![1111](https://github.com/user-attachments/assets/491c31b2-dad8-40fa-8e6d-e063f0ea3e80)

**Comment by jingyaogong** [comment]
是的，相比于逻辑和数学问题，它只能回答一些简单的训练中见过的常识。

或者说100M左右大小的模型还不具备什么推理能力，更重要的是训练数据严重不足，数据量再扩大100倍 & 模型扩大到500M~1B也许才能具备简单“逻辑”。

项目目前停留在：跑通大模型训练的流程，初窥一下LLM的运行逻辑，还没有办法涉及榜单和效果测评。

下面效果的提升就只能交给scaling law了

~感谢指正！

**Comment by cts2021** [comment]
> 是的，相比于逻辑和数学问题，它只能回答一些简单的训练中的常识问题。
> 
> 或者说100M左右大小的模型还不具备什么推理能力，更重要的是训练数据严重不足，数据量再扩大100倍 & 模型扩大到500M~1B也许才能具备简单“逻辑”。
> 
> 项目目前停留在：跑通大模型训练的流程，初窥一下LLM的运行逻辑，还没有办法涉及榜单和效果测评。
> 
> 下面效果的提升就只能交给scaling law了
> 
> ~感谢指正！

您的工作超成果已经非常给力了。

**Comment by wuwenjie1992** [comment]
能跑通大模型预训练、指令微调、对齐等流程就已经非常棒了

**Comment by chuanzhubin** [comment]
哈哈，用逻辑题来拷问minimind，太狠了吧
