### ISSUE TITLE
不算是问题，简单讨论下pretrain eval的效果

### ISSUE THREAD

**Issue by cpp2016** [jingyaogong/minimind#78]
我预训练了一个15M的模型，loss下降从9.2到2.5左右，与大家的报告相近

pretrain eval进行接龙时的结果如下：存在大量重复
![image](https://github.com/user-attachments/assets/e2eada7c-d7dd-49e4-abb1-9ca882b7d337)

这种情况是正常的吗

**Comment by jingyaogong** [comment]
正常，一个是15M太小，无监督数据预训练学好更难
一个是预训练数据的质量偏低，minimind主要依靠SFT阶段更多的高质量数据提升最后的问答效果

26M结果（会好一些）：
![image](https://github.com/user-attachments/assets/e0144826-d38a-4597-a7f1-f607db9ee857)
