### ISSUE TITLE
训练一个1B的模型需要的显存

### ISSUE THREAD

**Issue by cts2021** [jingyaogong/minimind#8]
根据MiniMind (218M)的显存占用，1B需要50GB+的显存吗？

**Comment by jingyaogong** [comment]
显存占用可以参考：[https://github.com/hiyouga/LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory)：

\* *估算值*

| 方法               | 精度 |   7B  |  13B  |  30B  |   70B  |  110B  |  8x7B |  8x22B |
| ----------------- | ---- | ----- | ----- | ----- | ------ | ------ | ----- | ------ |
| Full              | AMP  | 120GB | 240GB | 600GB | 1200GB | 2000GB | 900GB | 2400GB |

我试了一下，`batch-size=1`时，训练1B模型（具体是1048M）大约占用18个G的显存

个人2*3090资源就完全吃不消了，很慢，大约半个月跑一个epoch

另外拓展到1B+的话，其实就和llama3-8B、qwen2-1.8B这些模型没有本质区别了（重复造轮），可以直接用它们为基础做进一步微调。

本项目探索的是Transformer-Decoder在小参数上的可行性，跑通大模型的训练全流程。

效果的事情只能交给有更大规模和能力的商业公司来探索哈哈。

感谢支持！

**Comment by cts2021** [comment]
好的，谢谢您的及时解答。
