### ISSUE TITLE
求助，sft数据处理完后是不会使用分词器转码的吗？

### ISSUE THREAD

**Issue by Enter10000** [jingyaogong/minimind#80]
我自己制作了一份数据集，不怎么大，我的目的不是让它会答题，而是希望能模仿我给的q和a的风格，生成类似的答案，哪怕不通顺都行。我按照公开sft数据集的格式制作的，数据处理也正常，可想要训练的时候指定要pretrain文件，我修改文件名后，运行又加载不出来，报错识别错误。
代码我是用git本地部署的，也问过gpt解决了一些问题，但现在就卡在这了，是必须要用pretrain数据集吗

**Comment by jingyaogong** [comment]
@Enter10000 
具体错误是什么
另外 你的数据集内容长什么样

**Comment by Enter10000** [comment]
好像是我想错了，我是想直接只用sft数据训练大模型，不是微调的那种，所以一直不行。
