### ISSUE TITLE
我有个比较粗浅疑问：PT、SFT、DPO这些不同的训练方法在本质上是一样的？

### ISSUE THREAD

**Issue by chuanzhubin** [jingyaogong/minimind#87]
我有个比较粗浅疑问：PT、SFT、DPO这些不同的训练方法在本质上是一样的？
当我在问这个问题的时候就在想，他们都在计算loss，以一定的学习率去梯度下降。那么他们在这个层面上是不是一样的。
只是设计了不同的loss函数，不同的学习率优化器。

**Comment by jingyaogong** [comment]
基本上是的，区别只有数据和loss的目标
