### ISSUE TITLE
请问Lora比全量微调更耗时是什么原因，正常吗？

### ISSUE THREAD

**Issue by srconly** [jingyaogong/minimind#88]
全参数微调150min
![full_sft](https://github.com/user-attachments/assets/6ad584a7-16d5-43c7-a632-032dc4f0dc5e)
lora微调260min，我设置的r=2，
![lora_sft](https://github.com/user-attachments/assets/7072c766-d1cc-46b2-957e-4195ba49cf58)
dim都是512

**Comment by jingyaogong** [comment]
正常，这里的LORA训练只是用 `get_all_linear` 简单的跑起来
实际中不会对100%的所有线性层做低秩微调，全加的话在原有模型不量化的情况下可能反而会轻微增加时间开销

这里可以只对q,k投影层加低秩矩阵
```
def find_linear_with_keys(model, keys=["wq", "wk"]):
    cls = torch.nn.Linear
    linear_names = []
    for name, module in model.named_modules():
        if isinstance(module, cls):
            for key in keys:
                if key in name:
                    linear_names.append(name)
                    break
    return linear_names
```

全参SFT时间：
![image](https://github.com/user-attachments/assets/e12ac750-e706-4c17-b8bc-fa9cdcabe6b8)
LORA-QK时间（参考[最新代码](https://github.com/jingyaogong/minimind/blob/master/4-lora_sft.py)），变快了一些：
![image](https://github.com/user-attachments/assets/de45106b-9f99-47f1-a821-e1378094e643)
LORA-Last-Linear时间（更快）：
![image](https://github.com/user-attachments/assets/7a6ecd3f-c540-44f9-881f-2364a2b80841)
