### ISSUE TITLE
对比full_sft，lora_sft每轮需要的训练时间更长

### ISSUE THREAD

**Issue by Aorunfa** [jingyaogong/minimind#91]
单机2张4090，python环境，训练设置完全相同，full_sft每轮的训练时间大约76分钟，lora_sft则需要117分钟；请问大佬这个耗时正常吗？不正常的话有可能是什么原因导致。
<img width="845" alt="full_sft" src="https://github.com/user-attachments/assets/5a42fd83-c928-4777-abd1-224daa6e3051">

<img width="913" alt="lora_sft" src="https://github.com/user-attachments/assets/c6d585b4-6301-4a2b-921f-ef8d72340557">

**Comment by srconly** [comment]
https://github.com/jingyaogong/minimind/issues/88
作者在这里给过回答

**Comment by jingyaogong** [comment]
不知道使用的是哪个版本代码，对哪些linear_layer做的lora

**Comment by Aorunfa** [comment]
> #88 作者在这里给过回答

感谢
