### ISSUE TITLE
加入常见的 benchmark 以及垂直领域评测

### ISSUE THREAD

**Issue by lyc8503** [jingyaogong/minimind#92]
README 中的演示效果看起来不错，是否可以同时加入一些常见的评测指标（例如 Qwen 给出的：https://huggingface.co/Qwen/Qwen2-72B#qwen2-72b-performance），以和现有的 LLM 进行对比。

目前文档中只有 C-Eval，四选一总体 25% 左右的准确率似乎并不能说明模型学会了知识。

不过作为参数量远小于常规（甚至小于 BERT）的 LLM，用户肯定不会有过高的期望，如果较小的参数量不能支持"通用"的泛化能力，是否能用垂直领域数据训练一个专用的语言模型，在某些 benchmark 上达到比目前更好的效果。（毕竟垂直领域可能是自己训练的 language model 比较有实际用途的地方）

**Comment by jingyaogong** [comment]
关于您提到的C-Eval评测结果，确实会探索更多的benchmark，并计划在未来说明中加入更多评测结果，以更全面地展示模型的能力。关于垂直领域模型的建议，非常认同，考虑未来训练更新医学问答、心理助手、专利问答等微调版更有潜力的模型。
