### ISSUE TITLE
咨询如何处理超长的pretrain数据集

### ISSUE THREAD

**Issue by qiukeren** [jingyaogong/minimind#93]
当我pretrain 使用 pd.read_json 的时候

```
    model, tokenizer = init_model()
    df = pd.****read_json****(args.data_path)
    df = df.sample(frac=1.0)
    train_ds = PretrainDataset(df, tokenizer, max_length=max_seq_len)
    train_sampler = DistributedSampler(train_ds) if ddp else None
    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        pin_memory=True,
        drop_last=False,
        shuffle=False,
        num_workers=args.num_workers,
        sampler=train_sampler
    )

```

使用 minimind 筛选出来的数据，（text length < 512）约4.4G ，500万行，
当读取(pd.read_json)的时候，内存占用峰值会到24G左右，
最终读取完的内存占用大约在6G左右，
使用pd.read_csv应该也是类似的占用，一大部分空间会被重复使用而浪费掉，

训练wenge-research/yayi2_pretrain_data （500G，筛选text length < 512之后还剩25G数据）或者更大一点的SkyPile数据集则会导致内存过大无法训练

有没有办法削减这一步的内存占用，以及削减后面GPU的内存占用？
或者说，在针对大预言处理超大数据集的时候，一般采取怎么样的方案？
（如果是按照数据大小进行分片处理，那么处理完成后的pth文件最终应该怎样合并在一起？）

**Comment by jingyaogong** [comment]
这个问题就是一些偏工程方面的优化，读取大型数据集是软件/数据处理行业内任意场景都会遇到的，这并非LLM独家专属

例如读取的时候可以用chunksize分片
```
chunksize = 10 ** 6  # 每次读取100万行
for chunk in pd.read_json(args.data_path, lines=True, chunksize=chunksize):
    # 对每个块进行处理，例如筛选、预处理等
    chunk = chunk[chunk['text'].str.len() < 512]
    # 将处理后的数据保存到磁盘或内存中（视具体情况而定）
```

dask并行处理和延迟计算（没试过）
```
import dask.dataframe as dd

df = dd.read_json(args.data_path, lines=True)
```

应对超大规模数据集，用更高效的数据加载器 `IterableDataset` （这里用法不展开）

....等等方案

所以MiniMind给出的demo还存在着无数的方向可以深入优化
