### ISSUE TITLE
请问，kv_cache缓存是什么时候清空的？

### ISSUE THREAD

**Issue by cqcracked** [jingyaogong/minimind#94]
用0-eval-pretrain.py进行预测推理的时候，推理第2个问题，照理应该清空第一个问题的kv_cache缓存，但并没有看见清空kv_cache缓存。

**Comment by jingyaogong** [comment]
![image](https://github.com/user-attachments/assets/4f773fc1-3e10-4d12-97eb-e9e217181334)
每次generate的时候第一次都会初始化新的kv_cache

这回答了你 ”照理应该清空第一个问题的kv_cache缓存，但并没有看见清空kv_cache缓存。”

**Comment by cqcracked** [comment]
感谢！
