### ISSUE TITLE
关于LLM的训练流程

### ISSUE THREAD

**Issue by ZKCCZ** [jingyaogong/minimind#98]
感谢您的分享，入门LLM变得更加清晰简单。然而由于我知识欠缺的比较多，因此有一些问题：
1. Pretrain、SFT（单/多轮）、RLHF这一套流程是目前最好的LLM的训练流程吗？为什么是这一套流程？希望您可以给一些入门LLM论文的建议，或者这一套流程的证明论文~
2. 您如何搜集和关注目前最新或优质的中文数据集？

提前感谢您的回答！！

**Comment by jingyaogong** [comment]
1、可以看Meta官方论文，这是（ChatGPT火起来之后）全世界最早也是通用开源LLM的训练范式[llama1](https://arxiv.org/abs/2302.13971), [llama2](https://ai.meta.com/research/publications/llama-2-open-foundation-and-fine-tuned-chat-models/); OpenAI在GPT-3以前也是有arxiv论文发布的，也就是2020年及以前的早期GPT系列：[GPT1](https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf), [GPT2](https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf), [GPT3](https://arxiv.org/pdf/2005.14165)

2、数据集可以关注这个项目：[Awesome-Chinese-LLM](https://github.com/HqWu-HITCS/Awesome-Chinese-LLM)
